<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="web/css/style.css">
    <title>blog</title>
</head>
<body>
    <h1>My Blog</h1>
    <div class="strip"></div>

    <a href="/posts/edit" class="add-post">add post</a>

    <div class="post_container">
        <?= $posts ?>
    </div>
</body>
</html>

